title: George Burgess
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url:
baseurl: "https://georgeburgess0827.github.io/long-haul/"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 3

navigation:
 - title: Blog
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: GeorgeBurgess0827
   twitter:
   facebook: georgeburgessjr
   linkedin:
   email:

google_analytics: ""
