title: George Burgess
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url:
baseurl: "https://georgeburgess0827.github.io/long-haul/"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 3

navigation:
 - title: Blog
   url: /index.html
 - title: About
   url: /about
 - title: Portfolio
   url: https://georgeburgess.carbonmade.com/
 - title: Contact
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   linkedin:
   email: brimaidesigns@gmail.com

google_analytics: ""
